export const FETCH_BRANCH_FAILURE = "FETCH_BRANCH_FAILURE";
export const FETCH_BRANCH_REQUEST = "FETCH_BRANCH_REQUEST";
export const FETCH_BRANCH_SUCCESS = "FETCH_BRANCH_SUCCESS";

export const CREATE_BRANCH_SUCCESS = "CREATE_BRANCH_SUCCESS";
export const DELETE_BRANCH_SUCCESS = "DELETE_BRANCH_SUCCESS";
export const UPDATE_BRANCH_SUCCESS = "UPDATE_BRANCH_SUCCESS";
export const SINGLE_BRANCH_SUCCESS = "SINGLE_BRANCH_SUCCESS";
export const MULTIPLE_BRANCH_SUCCESS = "MULTIPLE_BRANCH_SUCCESS";