export const FETCH_DELIVERY_FAILURE = "FETCH_DELIVERY_FAILURE";
export const FETCH_DELIVERY_REQUEST = "FETCH_DELIVERY_REQUEST";
export const FETCH_DELIVERY_SUCCESS = "FETCH_DELIVERY_SUCCESS";

export const CREATE_DELIVERY_SUCCESS = "CREATE_DELIVERY_SUCCESS";
export const DELETE_DELIVERY_SUCCESS = "DELETE_DELIVERY_SUCCESS";
export const UPDATE_DELIVERY_SUCCESS = "UPDATE_DELIVERY_SUCCESS";
export const SINGLE_DELIVERY_SUCCESS = "SINGLE_DELIVERY_SUCCESS";
export const MULTIPLE_DELIVERY_SUCCESS = "MULTIPLE_DELIVERY_SUCCESS";