export const FETCH_GIFT_ASSIGN_FAILURE = "FETCH_GIFT_ASSIGN_FAILURE";
export const FETCH_GIFT_ASSIGN_REQUEST = "FETCH_GIFT_ASSIGN_REQUEST";
export const FETCH_GIFT_ASSIGN_SUCCESS = "FETCH_GIFT_ASSIGN_SUCCESS";

export const CREATE_GIFT_ASSIGN_SUCCESS = "CREATE_GIFT_ASSIGN_SUCCESS";
export const DELETE_GIFT_ASSIGN_SUCCESS = "DELETE_GIFT_ASSIGN_SUCCESS";
export const UPDATE_GIFT_ASSIGN_SUCCESS = "UPDATE_GIFT_ASSIGN_SUCCESS";
export const SINGLE_GIFT_ASSIGN_SUCCESS = "SINGLE_GIFT_ASSIGN_SUCCESS";