export const FETCH_GIFT_FAILURE = "FETCH_GIFT_FAILURE";
export const FETCH_GIFT_REQUEST = "FETCH_GIFT_REQUEST";
export const FETCH_GIFT_SUCCESS = "FETCH_GIFT_SUCCESS";

export const CREATE_GIFT_SUCCESS = "CREATE_GIFT_SUCCESS";
export const DELETE_GIFT_SUCCESS = "DELETE_GIFT_SUCCESS";
export const UPDATE_GIFT_SUCCESS = "UPDATE_GIFT_SUCCESS";
export const SINGLE_GIFT_SUCCESS = "SINGLE_GIFT_SUCCESS";
export const MULTIPLE_DELETE_GIFT_SUCCESS = "MULTIPLE_DELETE_GIFT_SUCCESS";