export const FETCH_INVOICE_FAILURE = "FETCH_INVOICE_FAILURE";
export const FETCH_INVOICE_REQUEST = "FETCH_INVOICE_REQUEST";
export const FETCH_INVOICE_SUCCESS = "FETCH_INVOICE_SUCCESS";

export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
export const UPDATE_INVOICE_SUCCESS = "UPDATE_INVOICE_SUCCESS";
export const SINGLE_INVOICE_SUCCESS = "SINGLE_INVOICE_SUCCESS";
export const MULTIPLE_DELETE_INVOICE_SUCCESS = "MULTIPLE_DELETE_INVOICE_SUCCESS";