export const FETCH_LEAD_FAILURE = "FETCH_LEAD_FAILURE";
export const FETCH_LEAD_REQUEST = "FETCH_LEAD_REQUEST";
export const FETCH_LEAD_SUCCESS = "FETCH_LEAD_SUCCESS";

export const CREATE_LEAD_SUCCESS = "CREATE_LEAD_SUCCESS";
export const DELETE_LEAD_SUCCESS = "DELETE_LEAD_SUCCESS";
export const UPDATE_LEAD_SUCCESS = "UPDATE_LEAD_SUCCESS";
export const SINGLE_LEAD_SUCCESS = "SINGLE_LEAD_SUCCESS";
export const MULTIPLE_DELETE_LEAD_SUCCESS = "MULTIPLE_DELETE_LEAD_SUCCESS";
export const TODAYS_LEADS_SUCCESS = "TODAYS_LEADS_SUCCESS";

export const BULK_LEAD_SUCCESS = "BULK_LEAD_SUCCESS"; 