export const FETCH_QUOTATION_FAILURE = "FETCH_QUOTATION_FAILURE";
export const FETCH_QUOTATION_REQUEST = "FETCH_QUOTATION_REQUEST";
export const FETCH_QUOTATION_SUCCESS = "FETCH_QUOTATION_SUCCESS";

export const CREATE_QUOTATION_SUCCESS = "CREATE_QUOTATION_SUCCESS";
export const DELETE_QUOTATION_SUCCESS = "DELETE_QUOTATION_SUCCESS";
export const UPDATE_QUOTATION_SUCCESS = "UPDATE_QUOTATION_SUCCESS";
export const SINGLE_QUOTATION_SUCCESS = "SINGLE_QUOTATION_SUCCESS";
export const MULTIPLE_DELETE_QUOTATION_SUCCESS = "MULTIPLE_DELETE_QUOTATION_SUCCESS";
export const CHANGE_STATUS_QUOTATION_SUCCESS = "CHANGE_STATUS_QUOTATION_SUCCESS";
export const CHANGE_QUOTATION_TO_INVOICE_SUCCESS = "CHANGE_QUOTATION_TO_INVOICE_SUCCESS";