export const FETCH_SIGNIN_USER_FAILURE = "FETCH_SIGNIN_USER_FAILURE";
export const FETCH_SIGNIN_USER_REQUEST = "FETCH_SIGNIN_USER_REQUEST";
export const FETCH_SIGNIN_USER_SUCCESS = "FETCH_SIGNIN_USER_SUCCESS";