export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const DECODE_USER_SUCCESS = "DECODE_USER_SUCCESS";

export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const SINGLE_USER_SUCCESS = "SINGLE_USER_SUCCESS";
export const MULTIPLE_DELETE_USER_SUCCESS = "MULTIPLE_DELETE_USER_SUCCESS";